spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password
    database-platform: org:hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: true
    change-log: db/changelog/db-changelog-master.yaml
logging:
  level:
    org.hibernate.sql: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
conturintegrator:
  service:
    uri_brief_report: https://focus-api.kontur.ru/api3/briefReport
    uri_basic_details: https://focus-api.kontur.ru/api3/req
    key: 3208d29d15c507395db770d0e65f3711e40374df