spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contur-api-integrator
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/db-changelog-master.yaml
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
conturintegrator:
  service:
    uri_brief_report: https://focus-api.kontur.ru/api3/briefReport
    uri_basic_details: https://focus-api.kontur.ru/api3/req
    key: 3208d29d15c507395db770d0e65f3711e40374df