spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contur-api-integrator
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/db-changelog-master.yaml
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
