version: '3'
services:
  Liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: Liquibase_container
    depends_on:
      - PostgreSQL
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog/
    command: --defaults-file=src/main/resources/db/changelog/db-changelog-master.yaml update

  PostgreSQL:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DATABASE: contur-api-integrator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"